# Generated by Django 4.1.7 on 2023-03-27 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_student_class_name_studentclass_student_class_and_more'),
        ('student_attendance', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentclass'),
        ),
    ]
