# Generated by Django 4.1.7 on 2023-03-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0006_alter_studentattendance_student_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='student_class',
        ),
    ]
