# Generated by Django 4.1.7 on 2023-03-14 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_student_class_name_studentclass_student_class_and_more'),
        ('student_marks', '0005_subjectmarks_std_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmarks',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo'),
        ),
    ]
