# Generated by Django 4.1.7 on 2023-03-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_marks', '0007_remove_subjectmarks_std_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectmarks',
            old_name='student_id',
            new_name='student_name',
        ),
    ]
