# Generated by Django 4.1.7 on 2023-03-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_marks', '0009_alter_subjectmarks_english_alter_subjectmarks_hindi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmarks',
            name='Total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
