# Generated by Django 4.1.7 on 2023-03-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_student_class_name_studentclass_student_class_and_more'),
        ('student_marks', '0011_rename_total_subjectmarks_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmarks',
            name='exam_type',
            field=models.CharField(choices=[('Half yearly', 'Half yearly'), ('Annual', 'Annual')], default='Half yearly', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectmarks',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo'),
        ),
    ]
