# Generated by Django 4.1.7 on 2023-03-30 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_student_class_name_studentclass_student_class_and_more'),
        ('student_marks', '0012_subjectmarks_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmarks',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='student.studentinfo'),
        ),
    ]
