# Generated by Django 4.1.7 on 2023-03-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('student_class', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.TextField(max_length=10)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
