# Generated by Django 4.1.7 on 2023-03-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentclass_alter_studentinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
