# Generated by Django 4.1.7 on 2023-03-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentinfo_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
