# Generated by Django 4.1.7 on 2023-03-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentinfo_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclass',
            old_name='student_class',
            new_name='student_class_name',
        ),
    ]
