# Generated by Django 4.1.7 on 2023-03-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_student_class_studentclass_student_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclass',
            old_name='student_class_name',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='student_class',
            new_name='std_class',
        ),
    ]
