# Generated by Django 4.1.7 on 2023-03-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
